export const TYPES = {
  CHANGE_NAME: "CHANGE_NAME",
  CLEAR_PURCHASES: "CLEAR_PURCHASES",

  ADD_PURCHASES: "ADD_PURCHASES",

  SHOW_LIMIT_MODAL: "SHOW_LIMIT_MODAL",
  CLOSE_LIMIT_MODAL: "CLOSE_LIMIT_MODAL",
};
