export const TYPES = {
  CHANGE_NAME: "CHANGE_NAME",
  CLEAR_PURCHASES: "CLEAR_PURCHASES",

  ADD_PURCHASES: "ADD_PURCHASES",

  SHOW_LIMIT_MODAL: "SHOW_LIMIT_MODAL",
  CLOSE_LIMIT_MODAL: "CLOSE_LIMIT_MODAL",

  GET_TABLE_DATA_REQUEST: "GET_TABLE_DATA_REQUEST",
  GET_TABLE_DATA_REQUEST_SUCCESS: "GET_TABLE_DATA_REQUEST_SUCCESS",
  GET_TABLE_DATA_REQUEST_ERROR: "GET_TABLE_DATA_REQUEST_ERROR",

  GET_MESSAGES_REQUEST: "GET_MESSAGES_REQUEST",
  GET_MESSAGES_REQUEST_SUCCESS: "GET_MESSAGES_REQUEST_SUCCESS",
  GET_MESSAGES_REQUEST_ERROR: "GET_MESSAGES_REQUEST_ERROR",

  SEND_MESSAGE_REQUEST: "SEND_MESSAGE_REQUEST",
  SEND_MESSAGE_REQUEST_SUCCESS: "SEND_MESSAGE_REQUEST_SUCCESS",
  SEND_MESSAGE_REQUEST_ERROR: "SEND_MESSAGE_REQUEST_ERROR",

  DELETE_MESSAGE_REQUEST: "DELETE_MESSAGE_REQUEST",
  DELETE_MESSAGE_REQUEST_SUCCESS: "DELETE_MESSAGE_REQUEST_SUCCESS",
  DELETE_MESSAGE_REQUEST_ERROR: "DELETE_MESSAGE_REQUEST_ERROR",

  EDIT_MESSAGE_REQUEST: "EDIT_MESSAGE_REQUEST",
  EDIT_MESSAGE_REQUEST_SUCCESS: "EDIT_MESSAGE_REQUEST_SUCCESS",
  EDIT_MESSAGE_REQUEST_ERROR: "EDIT_MESSAGE_REQUEST_ERROR",

  UPADATE_MESSAGE_LIKES_REQUEST: "UPADATE_MESSAGE_LIKES_REQUEST",
  UPADATE_MESSAGE_LIKES_REQUEST_SUCCESS:
    "UPADATE_MESSAGE_LIKES_REQUEST_SUCCESS",
  UPADATE_MESSAGE_LIKES_REQUEST_ERROR: "UPADATE_MESSAGE_LIKES_REQUEST_ERROR",

  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_ERROR: "GET_USERS_ERROR",

  ADD_USERS_REQUEST: "ADD_USERS_REQUEST",
  ADD_USERS_SUCCESS: "ADD_USERS_SUCCESS",
  ADD_USERS_ERROR: "ADD_USERS_ERROR",
};
